package com.asad.metappgallery.detailScreen.presentation.screen

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.requiredHeight
import androidx.compose.foundation.layout.requiredSize
import androidx.compose.foundation.layout.requiredWidth
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.Card
import androidx.compose.material.CircularProgressIndicator
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawWithCache
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.asad.metappgallery.app.UiState
import com.asad.metappgallery.core.presentation.NetworkImage
import com.asad.metappgallery.core.util.ComposeUtil
import com.asad.metappgallery.detailScreen.presentation.component.TagsContent
import com.asad.metappgallery.detailScreen.presentation.util.ObjectDetailScreen
import com.asad.metappgallery.detailScreen.presentation.viewModel.ObjectDetailViewModel
import com.asad.metappgallery.searchScreen.presentation.component.CustomAppBar
import com.asad.metappgallery.searchScreen.presentation.component.TouchableScale

private const val TAG = "DetailScreen"

@Composable
fun DetailScreen(
    viewModel: ObjectDetailViewModel,
    currentObjectId: String,
    onNavigationBack: () -> Unit,
) {
    BackHandler {
        viewModel.cancelFetchingData()
        onNavigationBack.invoke()
    }

    // This is supposed the be run only once
    LaunchedEffect(key1 = true) {
        viewModel.fetchObjectDetail(currentObjectId.toInt())
    }
    val uiState = ComposeUtil.rememberStateWithLifecycle(stateFlow = viewModel.uiState)

    val configuration = LocalConfiguration.current

    val scrollState = rememberScrollState()

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(color = MaterialTheme.colors.surface),
        contentAlignment = Alignment.Center,
    ) {
        val surfaceColor = MaterialTheme.colors.surface
        val statusBarColor = MaterialTheme.colors.primaryVariant

        when (uiState.value.objectDetailState) {
            UiState.Empty -> {}
            is UiState.Error -> {
                TouchableScale(onClick = {
//                    viewModel.fetchUserData(username = username)
                }) {
                    val errorMessage = "Error generated by asad"
//                        if (uiState.value.userData?.exception != null) {
//                            ExceptionMessageMapper.getProperMessageForException(uiState.value.userData!!.exception!!)
//                        } else {
//                            UserDetailString.FailedToFetchDataErrorMessage
//                        }
                    Text(
                        text = errorMessage,
                        style = MaterialTheme.typography.h6,
                        color = Color.White,
                        textAlign = TextAlign.Center,
                        modifier = Modifier
                            .align(Alignment.Center)
                            .padding(horizontal = 24.dp),
                    )
                }
            }

            UiState.Loading -> {
                CircularProgressIndicator(
                    modifier = Modifier
                        .requiredSize(48.dp)
                        .align(Alignment.Center),
                    color = Color.White,
                    strokeWidth = 4.dp,
                )
            }

            is UiState.Success -> {
                val data = uiState.value.objectDetailState.data!!

                (data?.primaryImageSmall ?: data?.primaryImage)?.let {
                    NetworkImage(
                        url = it,
                        modifier = Modifier
                            .align(Alignment.TopCenter)
                            .requiredWidth(
                                configuration.screenWidthDp.dp,
                            )
                            .requiredHeight(
                                configuration.screenWidthDp.dp,
                            )
                            .drawWithCache {
                                onDrawWithContent {
                                    drawContent()
                                    val topGradient = Brush.verticalGradient(
                                        colors = listOf(statusBarColor, Color.Transparent),
                                        startY = 0f,
                                        endY = 3 * size.height / 4,
                                    )
                                    drawRect(topGradient)
                                }
                            }
                            .graphicsLayer(),
                        imageModifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.FillBounds,
                    )
                }

                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .verticalScroll(scrollState),
                ) {
                    Box(
                        modifier = Modifier
                            .requiredHeight(configuration.screenWidthDp.dp)
                            .fillMaxWidth(),
                    ) {
                        Spacer(
                            modifier = Modifier
                                .fillMaxSize()
                                .drawWithCache {
                                    onDrawWithContent {
                                        drawContent()

                                        val bottomGradient = Brush.verticalGradient(
                                            colors = listOf(surfaceColor, Color.Transparent),
                                            startY = size.height,
                                            endY = size.height / 3,
                                        )
                                        drawRect(bottomGradient)
                                    }
                                },
                        )

                        Text(
                            text = data.objectName ?: data.artistDisplayName,
                            style = MaterialTheme.typography.h6.copy(
                                color = MaterialTheme.colors.onSecondary,
                            ),
                            modifier = Modifier
                                .align(Alignment.BottomStart)
                                .padding(horizontal = 24.dp, vertical = 16.dp),
                        )
                    }

                    Spacer(
                        modifier = Modifier
                            .height(16.dp)
                            .fillMaxWidth()
                            .background(surfaceColor),
                    )

                    Text(
                        text = ObjectDetailScreen.artistDisplayName(data.artistDisplayName),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )

                    Text(
                        text = ObjectDetailScreen.department(data.department),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(color = surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )

                    Text(
                        text = ObjectDetailScreen.classification(data.classification),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(color = surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )
                    Text(
                        text = ObjectDetailScreen.culture(data.culture),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(color = surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )
                    Text(
                        text = ObjectDetailScreen.portfolio(data.portfolio),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(color = surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )
                    Text(
                        text = ObjectDetailScreen.objectDate(data.objectDate),
                        style = MaterialTheme.typography.body2.copy(
                            color = MaterialTheme.colors.onSecondary,
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(color = surfaceColor)
                            .padding(horizontal = 24.dp, vertical = 12.dp),
                    )

                    data.tagModels?.let {
                        TagsContent(tags = it)
                    }

                    data.additionalImages?.let {
                        ObjectAdditionalImageContent(images = it, surfaceColor)
                    }

                    Spacer(
                        modifier = Modifier
                            .requiredHeight(configuration.screenWidthDp.dp - 100.dp)
                            .fillMaxWidth()
                            .background(surfaceColor),
                    )
                }
            }
        }

        CustomAppBar(
            title = uiState.value.objectDetailState.data?.title
                ?: uiState.value.objectDetailState.data?.objectName ?: "Details",
            onNavigateUp = onNavigationBack,
            isTransparent = true,
        )
    }
}

@Composable
fun ObjectAdditionalImageContent(images: List<String>, backgroundColor: Color) {
    val horizontalScrollState = rememberScrollState()

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .requiredHeight(200.dp)
            .background(backgroundColor)
            .horizontalScroll(state = horizontalScrollState)
            .padding(horizontal = 24.dp),
    ) {
        images.map {
            Card(
                modifier = Modifier
                    .requiredHeight(200.dp)
                    .padding(8.dp),
                shape = RoundedCornerShape(12.dp),
                elevation = 4.dp,
                backgroundColor = Color.LightGray,
            ) {
                NetworkImage(
                    url = it,
                    contentScale = ContentScale.Fit,
                    imageModifier = Modifier
                        .fillMaxSize()
                        .clip(RoundedCornerShape(4.dp)),
                )
            }
        }
    }
}
