package com.asad.metappgallery.galleryDetail.presentation.screen

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.requiredHeight
import androidx.compose.foundation.layout.requiredSize
import androidx.compose.foundation.layout.requiredWidth
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.CircularProgressIndicator
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawWithCache
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.asad.metappgallery.app.UiState
import com.asad.metappgallery.core.presentation.NetworkImage
import com.asad.metappgallery.core.util.ComposeUtil
import com.asad.metappgallery.galleryDetail.presentation.viewModel.GalleryDetailViewModel
import com.asad.metappgallery.galleryFinder.presentation.component.CustomAppBar
import com.asad.metappgallery.galleryFinder.presentation.component.TouchableScale

@Composable
fun GalleryDetailScreen(
    viewModel: GalleryDetailViewModel,
    currentObjectId: String,
    onNavigationBack: () -> Unit,
) {
    BackHandler {
        viewModel.cancelFetchingData()
        onNavigationBack.invoke()
    }

    // This is supposed the be run only once
    LaunchedEffect(key1 = true) {
        viewModel.fetchGalleryDetail(currentObjectId.toInt())
    }
    val uiState = ComposeUtil.rememberStateWithLifecycle(stateFlow = viewModel.uiState)

    val configuration = LocalConfiguration.current

    Box(
        modifier = Modifier.fillMaxSize()
            .background(color = MaterialTheme.colors.surface),
        contentAlignment = Alignment.Center,
    ) {
        val surfaceColor = MaterialTheme.colors.surface
        val statusBarColor = MaterialTheme.colors.primaryVariant

        when (uiState.value.galleryDetail) {
            UiState.Empty -> {}
            is UiState.Error -> {
                TouchableScale(onClick = {
//                    viewModel.fetchUserData(username = username)
                }) {
                    val errorMessage = "Error generated by asad"
//                        if (uiState.value.userData?.exception != null) {
//                            ExceptionMessageMapper.getProperMessageForException(uiState.value.userData!!.exception!!)
//                        } else {
//                            UserDetailString.FailedToFetchDataErrorMessage
//                        }
                    Text(
                        text = errorMessage,
                        style = MaterialTheme.typography.h6,
                        color = Color.White,
                        textAlign = TextAlign.Center,
                        modifier = Modifier
                            .align(Alignment.Center)
                            .padding(horizontal = 24.dp),
                    )
                }
            }
            UiState.Loading -> {
                CircularProgressIndicator(
                    modifier = Modifier
                        .requiredSize(48.dp)
                        .align(Alignment.Center),
                    color = Color.White,
                    strokeWidth = 4.dp,
                )
            }
            is UiState.Success -> {
                val data = uiState.value.galleryDetail.data

                (data?.primaryImageSmall ?: data?.primaryImage)?.let {
                    NetworkImage(
                        url = it,
                        modifier = Modifier
                            .align(Alignment.TopCenter)
                            .requiredWidth(
                                configuration.screenWidthDp.dp,
                            )
                            .requiredHeight(
                                configuration.screenWidthDp.dp,
                            )
                            .drawWithCache {
                                onDrawWithContent {
                                    drawContent()
                                    val topGradient = Brush.verticalGradient(
                                        colors = listOf(statusBarColor, Color.Transparent),
                                        startY = 0f,
                                        endY = 3 * size.height / 4,
                                    )
                                    drawRect(topGradient)
                                }
                            }
                            .graphicsLayer(),
                        imageModifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.FillBounds,
                    )
                }

                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .verticalScroll(rememberScrollState()),
                ) {
                    Box(
                        modifier = Modifier
                            .requiredHeight(configuration.screenWidthDp.dp)
                            .fillMaxWidth(),
                    ) {
                        Spacer(
                            modifier = Modifier
                                .fillMaxSize()
                                .drawWithCache {
                                    onDrawWithContent {
                                        drawContent()

                                        val bottomGradient = Brush.verticalGradient(
                                            colors = listOf(surfaceColor, Color.Transparent),
                                            startY = size.height,
                                            endY = size.height / 3,
                                        )
                                        drawRect(bottomGradient)
                                    }
                                },
                        )

                        Text(
                            text = data?.objectName ?: data?.artistDisplayName ?: "",
                            style = MaterialTheme.typography.h6.copy(
                                color = MaterialTheme.colors.onSurface,
                            ),
                            modifier = Modifier
                                .align(Alignment.BottomStart)
                                .padding(horizontal = 24.dp, vertical = 16.dp),
                        )
                    }

                    Spacer(
                        modifier = Modifier
                            .height(16.dp)
                            .fillMaxWidth()
                            .background(surfaceColor),
                    )

                    Spacer(
                        modifier = Modifier
                            .requiredHeight(configuration.screenWidthDp.dp - 100.dp)
                            .fillMaxWidth()
                            .background(surfaceColor),
                    )
                }
            }
        }
        CustomAppBar(
            title = uiState.value.galleryDetail.data?.title
                ?: uiState.value.galleryDetail.data?.objectName ?: "Details",
            onNavigateUp = onNavigationBack,
            isTransparent = true,
        )
    }
}
